apiVersion: v1
kind: Namespace
metadat:
  name: daangn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: daangn
  name: daangn-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: app-scg
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-scg
    spec:
      containers:
      - image: sce06147/project-daangn-sre:arm64
        imagePullPolicy: Always
        name: app-scg
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  namespace: daangn
  name: daangn-service
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: app-scg
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: daangn
  name: daangn-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-issuer"
spec:
  tls:
  - hosts:
    - api.hyunsu.scg.skku.ac.kr
    secretName: apihyunsu-tls
  rules:
  - host: api.hyunsu.scg.skku.ac.kr
    http:
      paths:
      - backend:
          service:
            name: daangn-service
            port:
              number: 80
        path: /
        pathType: Prefix
